### ISSUE TITLE
@cap-js/sqlite: nested properties in where clause of delete crash

### ISSUE THREAD

**Issue by sebastianesch** [cap-js/cds-dbs#159]
Hi CAP Team!

When deleting using nested properties:

```js
 const result = await DELETE.from(GroupMembers).where({'user.externalUserId': user.externalUserId })
```

I get the following error:
```sh
TypeError: Cannot read properties of undefined (reading 'map')
    at _entityTransitionsForTarget (/.../node_modules/@sap/cds/libx/_runtime/common/utils/resolveView.js:593:19)
```

In resolveView the  `from` input for function `_entityTransitionsForTarget` is:

```js
{
  join: "left",
  args: [
    {
      ref: [
        "user.db.GroupMembers",
      ],
      as: "GroupMembers",
    },
    {
      ref: [
        "user.db.Users",
      ],
      as: "user",
    },
  ],
  on: [
    {
      ref: [
        "user",
        "ID",
      ],
    },
    "=",
    {
      ref: [
        "GroupMembers",
        "user_ID",
      ],
    },
  ],
}
```
but in line 593 an attribute `ref` is expected, that is not there in the DELETE case.

```js
return from.ref.map((f, i) => { ... } // line 593
```

`from.ref` is undefined in this case.

| Your Project Name | N/A |
|:------------------|---------------------------------------|
| OData version     | v4                              |
| Node.js version   | v18.16.1                               |
| @sap/cds          | 7.0.2                                 |
| @sap/cds-compiler | 3.9.2                                |
| @sap/cds-dk       | 7.1.0                                 |
| @cap-js/sqlite | 1.0.1 |

Kind regards,
Sebastian

**Comment by patricebender** [comment]
I just tried it out and this still doesnt work. The db-service translates such a path expression to a join. However, if there are localized fields present, the whole `where` clause is put in a `from` filter which leads to a scoped query: `DELETE Books[author.name = 'Emily Bronte']:author` which doesnt work because non-fk traversals in infix filters are not allowed. If the localized fields are removed, we get the reported dump in `resolveView`:

```
> del =  DELETE.from(Books).where("author.name = 'Emily Brontë'");
Query {
  DELETE: {
    from: 'sap.capire.bookshop.Books',
    where: [ { ref: [ 'author', 'name' ] }, '=', { val: 'Emily Brontë' } ]
  }
}
> await del
Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at _entityTransitionsForTarget (/Users/patricebender/SAPDevelop/dev/cds/libx/_runtime/common/utils/resolveView.js:673:19)
```

How do we get this situation solved?

**Comment by sebastianesch** [comment]
@patricebender To support nested attributes in the where clause of delete statements, the nesting needs to be resolved into a subselect. `DELETE from Books where author in (SELECT ID from Authors where name = 'Emily Bontë'`.

If the plan is to not support nested attributes I would appreciate a hint in the documentation and a clear error message. ;)

**Comment by patricebender** [comment]
> `where author in (SELECT ID from Authors where name = 'Emily Bontë')`.
> 
> If the plan is to not support nested attributes I would appreciate a hint in the documentation and a clear error message. ;)

I will post my comment from the discussion of Bobs PR here as well:

That [To support nested attributes in the where clause of delete statements, the nesting needs to be resolved into a subselect]  would be great. However, first we need to be able to understand a token stream such as a where. If the where is just an array of `xpr` it is quite hard to interpret. Think of operator precedence etc...

If the token stream would be parsed in a tree like structure, where operator precedence is clear and where it is easy to tell where one operand begins and ends. I think the example here illustrates the problem:
https://github.com/cap-js/cds-dbs/blob/98106dcddcdcfab4955f113c18a1a7d3464d1494/db-service/test/cqn4sql/UPDATE.test.js#L73-L84

For `UPDATE` there is no way around transforming path expressions into subqueries. With a `DELETE`, the situation looks different, we could theoretically produce `DELETE FROM` with `join`s because most DBs implement this. However, `FROM` for `DELETE` is not ANSI SQL compliant, so rejecting such requests could also be an option. Ping @BobdenOs @johannes-vogel @stewsk
