### ISSUE TITLE
[postgresql] Slow queries with docker on windows

### ISSUE THREAD

**Issue by aschmidt93** [cap-js/cds-dbs#930]
I have set up postgresql locally in a docker container running on Docker Desktop (wsl2) as described in the documentation https://cap.cloud.sap/docs/guides/databases-postgres#using-docker. When I setup a new CDS project via `cds init` with sample data and  query it using .http files, the response time is about ~50ms which is rather slow as the database contains almost no tables nor data. Running the command directly inside the container takes <2ms as expected.

When I add postgresql to a bigger project with 88 tables and deploy it with some initial data, a query for selecting an entity with no data takes ~150ms.  

The entity:

```cds
entity Logs : managed, cuid {
          module    : String(100);
          severity  : String;
          message   : LargeString;
          timestamp : Timestamp;
}
```

The sql log:

`[sql] - SELECT to_jsonb(Logs.*) as _json_ FROM (SELECT to_char(Logs.createdAt, 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"') as "createdAt",Logs.createdBy as "createdBy",Logs.ID as "ID",Logs.module as "module",Logs.severity as "severity",Logs.message as "message",to_char(Logs.timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"') as "timestamp" FROM (SELECT Logs.createdAt,Logs.createdBy,Logs.ID,Logs.module,Logs.severity,Logs.message,Logs.timestamp FROM SystemService_Logs as Logs ORDER BY Logs.timestamp DESC NULLS LAST,Logs.ID ASC NULLS FIRST LIMIT $1) as Logs) as Logs 50`

When I run the query manually with node and 'pg', it takes ~50ms which is still not that fast.

This might be a setup problem involving windows and docker? What optimizations can be done? Is this something to add to the documentation?

Note: The issue can be resolved when installing postresql directly onto the machine and not using Docker.

**Comment by patricebender** [comment]
@BobdenOs can you help out here as your dev env looks quite similar?

**Comment by BobdenOs** [comment]
@aschmidt93 this issue seems related to a fundamental part of how WSL2 is implemented. Windows has had virtualization for quite some time the underlying technology for all Windows native virtualization is based upon `hyper-v`. While it is a very powerful technology it has its origins from Windows server distributed systems. Which comes with some drawbacks when using it fully locally. One of the drawbacks is the full fletched network card virtualization. This mostly results in a terrible networking performance between the windows host and the virtual machines. Which is especially noticeable when screen sharing from a virtual machine running on the local machine.

My development setup is based upon WSL2 for both docker and my development WSL2 Ubuntu. By having both layers in the WSL2 virtualization layer the virtual network card doesn't impact the networking performance.

I would recommend developing inside a WSL2 linux operating system. Even if you are not familiar with how linux works. It is very straight forward to setup from the store [here](https://apps.microsoft.com/detail/9nz3klhxdjp5?ocid=webpdpshare). When using Visual Studio Code there is a WSL2 plugin which makes it work just like any other directory on your machine [plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl). It also comes with the benefits of linux file system which especially nice for node projects as an npm install is much faster (I haven`t had a single install take a minute).

I hope this provided you some insights into the problem you stumbled upon. If you really want it fixed you would have to follow up with a hyper-v expert / dev as I am not aware of a way of fixing the hyper-v virtual network.

**Comment by aschmidt93** [comment]
Thank you for the insights. You should consider adding this to the documentation.
